version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_curso_java
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - cursojava_data:/var/lib/mysql

volumes:
  cursojava_data: